#!/usr/bin/env bash
# configures a new HAproxy as a load balancer to send traffic to both servers

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend leksyking.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 155201-web-01 54.89.118.196
        server 155201-web-02 54.175.136.180
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
