#!/usr/bin/env bash
# script that configures a  server to listen on port 80.

rm -rf /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
