#!/usr/bin/env bash
# script of task 0 but using less lines(shortt and sweeet)

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
